In [29]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
import pickle

In [30]:
model=load_model('model.keras')

with open('label_enconder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('OneHotEncoder.pkl','rb') as file:
    label_encoder_one=pickle.load(file)
with open('sclaer.pkl','rb') as file:
    scaler=pickle.load(file)

In [31]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [32]:
geo_encoded= label_encoder_one.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_one.get_feature_names_out(['Geography']))

f:\Mission\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [33]:
input_df=pd.DataFrame([input_data])

In [34]:
input_data=pd.concat([input_df.reset_index(drop=True),geo_encoded_df],axis=1)
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [35]:
input_df['Gender'] =label_encoder_gender.transform([input_df['Gender']])
input_df

f:\Mission\venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [36]:
#concatination one hot encoded data
input_df=pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [37]:
#scalling the data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [38]:
predication=model.predict(input_scaled)
predication

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step

array([[0.02113594]], dtype=float32)

In [39]:
predication_proba=predication[0][0]
predication_proba

np.float32(0.021135936)

In [40]:
if predication_proba > 0.5:
    print("The customer is likely to churn.")
else:
    print("The custoner is not likely to churn.")

The custoner is not likely to churn.